Chore/api reference query suggestions
influxdata/openapi pull request #431
Opened 2022-07-12 16:09 UTC by sunbryely-influxdata

https://github.com/influxdata/openapi/issues/395

`v2/query/suggestions`

2022-07-12 16:35 UTC, sanderson requested changes

2022-07-12 16:35 UTC, sanderson commented on src/common/paths/query_suggestions.yml
> +    Moved Permanently` status code. Please use `/api/v2/query/suggestions`.
This took me a second to process. Maybe call out the fact that the trailing slash is what causes the problem.

2022-07-12 16:35 UTC, sanderson commented on src/common/paths/query_suggestions.yml
> +          --header 'Authorization: Token INFLUX_TOKEN'
```suggestion
        curl --request GET 'INFLUX_URL/api/v2/query/suggestions' \
          --header 'Accept: application/json' \
          --header 'Authorization: Token INFLUX_TOKEN'
```

2022-07-12 16:35 UTC, sanderson commented on src/common/paths/query_suggestions.yml
> +    Returns a list of all query functions.
What makes these "query functions"? This is new nomenclature.

I feel like the original summary of this endpoint was correct. It returns a limited list of query/function suggestions. I'm just curious how this endpoint is even used. It seems like it's probably specific to the UI implementation to display functions in a specific context. I don't know what they used to determine which functions to return with this endpoint.

2022-07-12 16:35 UTC, sanderson commented on src/common/paths/query_suggestions.yml
> +                The url has been permanently moved. Use `/api/v2/query/suggestions`.
```suggestion
                The URL has been permanently moved. Use `/api/v2/query/suggestions`.
```

2022-07-12 16:35 UTC, sanderson commented on src/common/schemas/MovedPermanently.yml
> +      description: Response message with url of requested resource.
```suggestion
      description: Response message with URL of requested resource.
```

2022-07-12 16:35 UTC, sanderson commented on src/common/paths/query_suggestions.yml
> +              summary: Invalid url
```suggestion
              summary: Invalid URL
```

2022-07-12 16:35 UTC, sanderson commented on src/common/paths/query_suggestions.yml
> +        InfluxData has moved the url of the endpoint.
```suggestion
        InfluxData has moved the URL of the endpoint.
```

2022-07-25 14:33 UTC, jstirnaman approved these changes
👍

2022-07-26 14:51 UTC, sanderson approved these changes

2022-07-26 14:51 UTC, sanderson commented on src/common/paths/query_suggestions.yml
> +        on a column and keep the top n records. `top` uses the `_sortLimit` helper function.
Minor nit: It's not that they shouldn't be used in queries, it's just that they aren't meant to be used directly. They actually are used by other functions as primitives. I don't know if it's worth updating this verbiage, but just a thought. In that same vein, I don't know that the "Not recommended vs Recommended" is necessary.

2022-07-26 21:29 UTC, merged