chore: passwords API on cloud not supported
influxdata/openapi pull request #439
Opened 2022-07-15 14:45 UTC by wbaker85

Closes https://github.com/influxdata/idpe/issues/15092

Changing passwords is not supported through the InfluxDB Cloud API, and this PR updates the API docs for that.

2022-07-15 14:49 UTC, sanderson requested changes
Some minor suggestions and alternate calls to action.

2022-07-15 14:49 UTC, sanderson commented on src/common/paths/me_password.yml
> +    - Doesn't support changing user passwords through the API.
```suggestion
    InfluxDB Cloud does not support changing user passwords through the API.
    Use the InfluxDB Cloud user interface to update your password.
```

2022-07-15 14:49 UTC, sanderson commented on src/common/paths/users_userID_password.yml
> +    - Doesn't support changing user passwords through the API.
```suggestion
    InfluxDB Cloud does not support changing user passwords through the API.
    Use the InfluxDB Cloud user interface to update your password.
```

2022-07-15 15:31 UTC, wbaker85 commented on src/common/paths/me_password.yml
> +    - Doesn't support changing user passwords through the API.
Done, thanks!

2022-07-15 15:36 UTC, sanderson approved these changes

2022-07-18 10:04 UTC, SimonRichardson approved these changes

2022-07-18 12:55 UTC, merged