feat: document new provision setup api
influxdata/openapi pull request #440
Opened 2022-07-15 15:23 UTC by wbaker85

API documentation for the new `/api/v2private/provision/setup` endpoint.

2022-07-15 15:26 UTC, sanderson requested changes
Minor suggestions.

2022-07-15 15:26 UTC, sanderson commented on src/cloud/schemas/ProvisionSetupRequest.yml
> +    description: retention period for the additional bucket
```suggestion
    description: Username for the initial user.
  org:
    type: string
    description: Name for the initial organization.
  userID:
    type: string
    description: User ID to create the initial user with.
  orgID:
    type: string
    description: Organization ID to create the initial organization with.
  bucket:
    type: string
    description: Name of an additional bucket to create for the initial user and org.
  retentionSeconds:
    type: integer
    description: Retention period for the additional bucket.
```

2022-07-15 15:36 UTC, sanderson approved these changes

2022-07-15 17:33 UTC, saraghds approved these changes

2022-07-15 17:33 UTC, saraghds commented on src/cloud/schemas/ProvisionSetupRequest.yml
> +    description: Name of an additional bucket to create for the initial user and org.
maybe mention this is optional?

2022-07-18 10:04 UTC, SimonRichardson approved these changes

2022-07-18 19:51 UTC, merged