fix: replaced BadRequest.yml with Error.yml to fix CLI codegen
influxdata/openapi pull request #446
Opened 2022-07-20 21:55 UTC by Xenonic

In `tasks.yml`, the `BadRequest.yml` breaks Go codegen in the CLI tool when used as the 400 response schema, this PR replaces it with the working `Error.yml`.

2022-07-21 14:01 UTC, jstirnaman requested changes
We want to be specific when documenting errors. Let's correct it or fix the consumer problem.

2022-07-25 17:52 UTC, Xenonic commented
@jstirnaman sorry that was a bit of a hacky fix when working on the CLI, latest fixes codegen and should have no impact on the docs.

2022-07-26 18:53 UTC, jstirnaman approved these changes

2022-07-26 18:53 UTC, jstirnaman commented on src/cloud/paths/tasks.yml
> +      $ref: "../../common/responses/BadRequestError.yml"
@Xenonic Thanks for fixing this! I'm surprised OATS validation let it through. I made a similar mistake yesterday and OATS CI failed it.
FYI, I think `$ref` with siblings isn't technically valid OpenAPI, but it's a rule that we frequently break without problems (AFAIK).

2022-07-26 19:24 UTC, merged