first draft
influxdata/openapi pull request #451
Opened 2022-07-26 01:46 UTC by sunbryely-influxdata

2022-07-26 20:51 UTC, sunbryely-influxdata commented on src/svc/invocable-scripts/paths/scripts_scriptID_invoke.yml
> +    "401":
@jstirnaman 
When I `run make generate-all` i get this reference error
`Error opening file "/openapi/src/svc/invocable-scripts/schemas/AuthorizationError.yml" 
ENOENT: no such file or directory, open '/openapi/src/svc/invocable-scripts/schemas/Error.yml'
`

I added the file into the svc schemas folder to resolve the issue but I dont think thats a good solution. Additionally, I get a ref error in the docs-v2 when running the bundling command.

`[4] cloud/ref.yml:11146:11 at #/paths/~1api~1v2~1scripts~1{scriptID}~1invoke/post/responses/401

Can't resolve $ref

11144 |         type: string
11145 | "401":
11146 |   $ref: '#/paths/~1scripts/get/responses/401'
11147 | "404":
11148 |   content:
`

Would you happen to know whats causing this or what I might be doing incorrectly?

2022-07-27 19:07 UTC, jstirnaman requested changes
Some suggestions, but mostly concerned about that `name` request param.

2022-07-27 19:07 UTC, jstirnaman commented on src/svc/invocable-scripts/schemas/ScriptInvocationParams.yml
> +      Provide key-value pairs within this params object for parameters
```suggestion
    `params` contains key-value pairs that map values to the **params.keys** in a script.
    When you invoke a script with `params`, InfluxDB passes the values as  invocation parameters to the script.
```

2022-07-27 19:07 UTC, jstirnaman commented on src/svc/invocable-scripts/schemas/ScriptInvocationParams.yml
> +      Provide key-value pairs within this params object for parameters
Explanation is a work-in-progress.

2022-08-04 13:33 UTC, jstirnaman requested changes

2022-08-04 13:33 UTC, jstirnaman commented on src/svc/invocable-scripts/schemas/Error.yml
> +  properties:
We shouldn't need to copy Error and ErrorCode just for this svc.

2022-08-04 13:33 UTC, jstirnaman commented on src/svc/invocable-scripts/schemas/ErrorCode.yml
> +description: code is the machine-readable error code.
We shouldn't need to copy Error and ErrorCode just for this svc.

2022-08-08 20:17 UTC, jstirnaman approved these changes
One minor fix.

2022-08-08 20:17 UTC, jstirnaman commented on src/svc/invocable-scripts/schemas/ScriptHTTPResponseData.yml
> +  The response is user defined and dynamic.
```suggestion
  The response is user-defined and dynamic.
```

2022-08-08 21:51 UTC, merged