feat(scripts): add/remove labels APIs
influxdata/openapi pull request #490
Opened 2022-08-25 20:34 UTC by saraghds

This PR publishes new APIs on scripts that handle adding labels to a script and removing labels from a script:

```
PATCH /scripts/{id}/labels/add
PATCH /scripts/{id}/labels/remove
```

This also includes two new filters on the `GET /scripts` API that helps with filtering scripts by labels and a part of a label name: `labelNames` and `labelContains`

2022-08-25 21:35 UTC, jstirnaman approved these changes
Some suggestions and a question about params behavior.

2022-08-25 21:56 UTC, saraghds commented on src/svc/invocable-scripts/paths/scripts.yml
> +        If a script has a label containing this phrase, it will be returned.
They both apply to the query in the storage layer. The script has to have all labels in the `labelNames` AND also labels that include the phrase in `labelContains`

2022-08-30 13:51 UTC, StacieClark requested changes

2022-08-30 13:51 UTC, StacieClark commented on src/svc/invocable-scripts/schemas/ScriptAddLabelsRequest.yml
> +properties:
Can we have a list of label names object that used for both adding and removing?

2022-08-30 21:28 UTC, StacieClark approved these changes

2022-08-30 21:31 UTC, merged