Chore/api reference bucket schemas
influxdata/openapi pull request #537
Opened 2022-09-15 04:33 UTC by sunbryely-influxdata

- List Bucket Schemas
- Create Bucket Schemas
- Retrieve Bucket Schemas
- Update Bucket Schemas

2022-09-15 17:41 UTC, jstirnaman requested changes

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +    - [Using bucket schemas](https://www.influxdata.com/blog/new-bucket-schema-option-protect-from-unwanted-schema-changes/)
```suggestion
    - [Create a bucket with an explicit schema]({% INFLUXDB_DOCS_URL %}}/organizations/buckets/create-bucket/#create-a-bucket-with-an-explicit-schema)
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
>    summary: List all measurement schemas of a bucket
Looks like a need to expand the guide to using the API for bucket schemas?

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +        Only returns schemas owned by this organization.
```suggestion
        Only returns schemas owned by the specified organization.
```
a la Kelly

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +        Only returns schemas owned by this organization.
```suggestion
        Only returns schemas owned by the specified organization.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +        Only returns measurement schemas with this name.
```suggestion
        Only returns measurement schemas with the specified name.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +        The ID of the bucket to retrieve schemas from.
```suggestion
        A bucket ID.
        Lists measurement schemas for the specified bucket.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +    Retrieves a list of measurement [schemas]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#schema)
```suggestion
    Retrieves a list of explicitly defined measurement [schemas]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#schema)
```

Explicit only?

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +    Creates a measurement [schema]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#schema)
```suggestion
    Creates an explicit measurement [schema]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#schema)
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +        Only returns schemas owned by this organization.
```suggestion
        Only returns schemas owned by the specified organization.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +        Only returns schemas owned by this organization.
```suggestion
        Only returns schemas owned by the specified organization.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +        The ID of the bucket to add a schema to.
```suggestion
        A bucket ID.
        Adds a schema for the specified bucket.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +    Retrieves a measurement [schemas]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#schema).
```suggestion
    Retrieves a measurement [schema]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#schema).
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +        Only returns schemas owned by this organization.
```suggestion
        Only returns schemas owned by the specified organization.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +        Only returns schemas owned by this organization.
```suggestion
        Only returns schemas owned by the specified organization.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +        The ID of the bucket to retrieve schemas from.
```suggestion
        A bucket ID.
        Retrieves schemas for the specified bucket.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +    Retrieves a measurement [schemas]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#schema).
"explicit"?

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +        The ID of the measurement schema to retrieve.
```suggestion
        The measurement schema ID.
        Specifies the measurement schema to retrieve.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +    `type`, and `dataType` fields of the column can be updated.
```suggestion
    Use this endpoint to update the fields (`name`, `type`, and `dataType`) of measurement schema columns . 
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +    - The `name` of the measurement can't be updated.
```suggestion
    - You can't update the `name` of a measurement.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +        Only returns schemas owned by this organization.
```suggestion
        Only returns schemas owned by the specified organization.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +        Only returns schemas owned by this organization.
```suggestion
        Only returns schemas owned by the specified organization.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +        Organization ID.
```suggestion
        An organization ID.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +        Organization name.
```suggestion
        An organization name.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +        Organization ID.
```suggestion
        An organization ID.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +        The ID of the bucket to retrieve schemas from.
```suggestion
        A bucket ID.
        Specifies the bucket to retrieve schemas for.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +        The ID of the measurement schema to retrieve.
```suggestion
        A measurement schema ID.
        Retrieves the specified measurement schema.
```

2022-09-15 17:41 UTC, jstirnaman commented on src/cloud/schemas/MeasurementSchemaCreateRequest.yml
> +        The name of the measurement.
```suggestion
        The measurement name.
```

2022-09-20 17:11 UTC, sunbryely-influxdata commented on src/cloud/paths/measurements.yml
>    summary: List all measurement schemas of a bucket
@jstirnaman To clarify, are you asking for a guide within this description, or an external guide?

2022-10-05 14:46 UTC, jstirnaman requested changes

2022-10-05 14:46 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +    [schemas]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#schema) for a bucket.
```suggestion
    [schemas]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#schema) (`"schemaType": "explicit"`) for a bucket.
```

2022-10-05 14:46 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +    [schemas]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#schema) for a bucket.
The type value is `explicit`, so we should just say _explicit_ bucket schemas and link to a definition or explain "explicitly defined..."

2022-10-05 14:46 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +    Creates an explict measurement [schema]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#schema)
```suggestion
    Creates an _explict_ measurement [schema]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#schema)
```

2022-10-05 14:46 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
>            description: The current version of the measurement schema
```suggestion
          description: The current version of the measurement schema.
```

2022-10-05 14:46 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +        Only returns schemas owned by the specified organization.
```suggestion
        Specifies the organization that owns the schema.
```

2022-10-05 14:46 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +        Only returns schemas owned by the specified organization.
```suggestion
        Specifies the organization that owns the schema.
```

2022-10-05 14:46 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +        Only returns schemas owned by the specified organization.
```suggestion
        Specifies the organization that owns the schema.
```

2022-10-05 14:46 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +        Only returns schemas owned by the specified organization.
```suggestion
        Specifies the organization that owns the schema.
```

2022-10-05 14:46 UTC, jstirnaman commented on src/cloud/paths/measurements_measurementID.yml
> +        Retrieves the specified measurement schema.
```suggestion
        Updates the specified measurement schema.
```

2022-10-05 14:46 UTC, jstirnaman commented on src/cloud/schemas/MeasurementSchemaCreateRequest.yml
> +        The measurement name.
Add a link (glossary, etc.) for measurement or measurement name.

2022-10-06 19:32 UTC, jstirnaman approved these changes
A few minor fixes.

2022-10-06 19:32 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +    By default, buckets have _implicit_ schema-type (`"schemaType": "implicit"`)
```suggestion
    By default, buckets have an _implicit_ schema-type (`"schemaType": "implicit"`)
```

2022-10-06 19:32 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +    that conform to your data.
```suggestion
    that conforms to your data.
```

2022-10-06 19:32 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +    By default, buckets have _implicit_ schema-type (`"schemaType": "implicit"`)
👍

2022-10-06 19:32 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +    that conform to your data.
```suggestion
    By default, buckets have an _implicit_ schema-type (`"schemaType": "implicit"`)
    that conforms to your data.
```

2022-10-06 19:32 UTC, jstirnaman commented on src/cloud/paths/measurements.yml
> +    - Buckets must be created with an "explict" `schemaType` in order to use
```suggestion
    - Buckets must be created with the "explict" `schemaType` in order to use
```

2022-10-07 17:20 UTC, merged