Chore/api reference dbrp
influxdata/openapi pull request #608
Opened 2022-11-08 22:09 UTC by sunbryely-influxdata

Database Retention Policy Mappings Endpoints

- Get DBRPs
- Create DBRP
- Get DBRP
- Update DBRP
- Delete DBRP

2022-11-09 23:39 UTC, jstirnaman requested changes

2022-11-09 23:39 UTC, jstirnaman commented on src/common/paths/dbrps_dbrpID.yml
> +        Only returns the specified organization.
```suggestion
        Specifies the organization that owns the DBRP mapping.
```

2022-11-09 23:39 UTC, jstirnaman commented on src/common/paths/dbrps_dbrpID.yml
> +        Only returns the specified organization.
```suggestion
        Specifies the organization that owns the DBRP mapping.
```

2022-11-09 23:39 UTC, jstirnaman commented on src/common/paths/dbrps_dbrpID.yml
>        description: Delete has been accepted
```suggestion
      description: Success. The delete is accepted.
```

Or one of these (not sure which is true):
 - "The DBRP mapping is deleted."
 - "The DBRP mapping is queued for deletion."

2022-11-09 23:39 UTC, jstirnaman commented on src/common/schemas/DBRP.yml
> +        The resource ID that InfluxDB uses to uniquely identify the task.
```suggestion
        The resource ID that InfluxDB uses to uniquely identify the database retention policy (DBRP) mapping.
```

Glossary link?

2022-11-09 23:39 UTC, jstirnaman commented on src/common/schemas/DBRPCreate.yml
> +      Identifies the [organization]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#organization) that owns the mapping.  orgID:
```suggestion
      Identifies the [organization]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#organization) that owns the mapping.
```

2022-11-09 23:39 UTC, jstirnaman commented on src/common/schemas/DBRP.yml
>        description: Mapping represents the default retention policy for the database specified.
```suggestion
      description: |
         If set to `true`, this DBRP mapping is the default retention policy
         for the database (specified by the `database` property's value).
```

2022-11-09 23:39 UTC, jstirnaman commented on src/common/schemas/DBRPCreate.yml
>      description: Mapping represents the default retention policy for the database specified.
```suggestion
    description: |
        Set to `true` to use this DBRP mapping as the default retention policy
        for the database (specified by the `database` property's value).
```

2022-11-09 23:39 UTC, jstirnaman commented on src/common/schemas/DBRPUpdate.yml
> +      description: Mapping represents the default retention policy for the database specifi
```suggestion
      description: |
         Set to `true` to use this DBRP mapping as the default retention policy
         for the database (specified by the `database` property's value).
         To remove the default mapping, set to `false`.
```

2022-11-22 17:06 UTC, sanderson approved these changes

2022-11-22 17:08 UTC, merged