chore: remove useless RequestBody for `Retry a task run`
influxdata/openapi pull request #90
Opened 2021-05-25 12:02 UTC by bednar

The request body for `Retry a task run` operation can be omitted. The server implementation only uses query parameters:

https://github.com/influxdata/influxdb/blob/00420fb54c79b9c3ce33b02fe5717a4365a32fe7/http/task_service.go#L1381.

And also the [OpenAPI](https://github.com/OpenAPITools/openapi-generator) generator generate useless model object with name `UNKNOWN_BASE_TYPE`.

2021-05-25 21:10 UTC, Asalem1 commented
This isn't useless unfortunately. It was recently added in due to CSRF protections that the API had added. Unfortunately, the tool the UI uses to generate functions `oats` isn't suited to modify content type on the UI so we would need to explicitly set that here

2021-05-25 21:11 UTC, Asalem1 requested changes
Here's the original PR with a link to the original issue:

https://github.com/influxdata/openapi/pull/79/files

2021-05-25 21:44 UTC, glinton commented
Asalem1 is correct, `RequestBody` was added so oats would always set the `content-type` on the request. Adding it as a parameter was attempted, but oats didn't populate the default value so the `RequestBody` version was adopted.

```yaml
    - in: header
      name: Content-Type
      schema:
        type: string
        default: 'application/json; charset=utf-8'
```

I'm wondering if setting the `Content-Type` parameter as `required` would help in any way.

2021-05-28 06:31 UTC, bednar commented
@glinton, @Asalem1 thanks for explanation

2021-05-28 06:31 UTC, closed without merging